# Server config
server:
  port: 8080

# DataSource
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://myserver:8505/db01?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://myserver:8505/db02?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
